// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5NTJOs5N8jACxbYkn-fHY-yvvt5eG1Kw',
    appId: '1:327053232361:android:382ea331b0cd75f5830878',
    messagingSenderId: '327053232361',
    projectId: 'final-graduation',
    storageBucket: 'final-graduation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHq654lbqACiF5f15dyGjrVaYNX-Bhi5o',
    appId: '1:327053232361:ios:9fd745722149f2c8830878',
    messagingSenderId: '327053232361',
    projectId: 'final-graduation',
    storageBucket: 'final-graduation.appspot.com',
    iosClientId: '327053232361-bq793285jdf8js3596vaqrp06rhk5bcv.apps.googleusercontent.com',
    iosBundleId: 'finalGraduation',
  );
}
